AWS_ACCESS_KEY_ID = 'AKIA2VJEQIYYTAXFMGWN'
AWS_SECRET_ACCESS_KEY = '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'

AWS_S3_ENDPOINT_URL = None

AWS_STORAGE_BUCKET_NAME_AR_MESSAGES_SOURCE = 'dev.ar-messages-source'
AWS_STORAGE_BUCKET_NAME_AR_MESSAGES = 'dev.ar-messages-processed'

AWS_QUEUE_NAME = 'g_dev_local' # 'prod-armessage-std'